// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39pIwEPy9CIm8N9YwLHu_h_29iIWkJaY',
    appId: '1:243816904975:web:c16747fddddd0544fda67a',
    messagingSenderId: '243816904975',
    projectId: 'flutterdemoapp-ede98',
    authDomain: 'flutterdemoapp-ede98.firebaseapp.com',
    databaseURL: 'https://flutterdemoapp-ede98-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemoapp-ede98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS24EStqL-j_sl31-do_6sRzYAK9Y0cG4',
    appId: '1:243816904975:android:5142d0f07a24bb0bfda67a',
    messagingSenderId: '243816904975',
    projectId: 'flutterdemoapp-ede98',
    databaseURL: 'https://flutterdemoapp-ede98-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemoapp-ede98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpGzPDxxiM6h-UX62jD3WpjZiJtxWV1A',
    appId: '1:243816904975:ios:5ad0245ed40df5dcfda67a',
    messagingSenderId: '243816904975',
    projectId: 'flutterdemoapp-ede98',
    databaseURL: 'https://flutterdemoapp-ede98-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemoapp-ede98.appspot.com',
    iosClientId: '243816904975-p7l1ds2ac4k0m8b0le9dmf8qvrc42nfi.apps.googleusercontent.com',
    iosBundleId: 'com.viibs.riverpodCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpGzPDxxiM6h-UX62jD3WpjZiJtxWV1A',
    appId: '1:243816904975:ios:e1fefe44e599fd82fda67a',
    messagingSenderId: '243816904975',
    projectId: 'flutterdemoapp-ede98',
    databaseURL: 'https://flutterdemoapp-ede98-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdemoapp-ede98.appspot.com',
    iosClientId: '243816904975-f9pqa3ks39falifq013mfgq27846m0q0.apps.googleusercontent.com',
    iosBundleId: 'com.viibs.riverpodCleanArchitecture.RunnerTests',
  );
}
